# Generated by Django 5.2.7 on 2025-10-01 22:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "task_name",
                    models.CharField(help_text="Name of the task", max_length=255),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Optional detailed description of the task",
                        null=True,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("health", "Health"),
                            ("work", "Work"),
                            ("study", "Study"),
                            ("personal", "Personal"),
                        ],
                        help_text="Category of the task",
                        max_length=20,
                    ),
                ),
                (
                    "due_date_time",
                    models.DateTimeField(help_text="When the task should be completed"),
                ),
                (
                    "notification",
                    models.BooleanField(
                        default=False,
                        help_text="Whether to send notifications for this task",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "Pending"), ("completed", "Completed")],
                        default="pending",
                        help_text="Current status of the task",
                        max_length=20,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When the task was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When the task was last updated"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, help_text="When the task was completed", null=True
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who owns this task",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Task",
                "verbose_name_plural": "Tasks",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "status"], name="task_manage_user_id_e188cd_idx"
                    ),
                    models.Index(
                        fields=["due_date_time"], name="task_manage_due_dat_5dd641_idx"
                    ),
                    models.Index(
                        fields=["category"], name="task_manage_categor_f92f69_idx"
                    ),
                ],
            },
        ),
    ]
