# Generated by Django 5.2.7 on 2025-10-02 20:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task_management", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={},
        ),
        migrations.RemoveIndex(
            model_name="task",
            name="task_manage_user_id_e188cd_idx",
        ),
        migrations.RemoveIndex(
            model_name="task",
            name="task_manage_due_dat_5dd641_idx",
        ),
        migrations.RemoveIndex(
            model_name="task",
            name="task_manage_categor_f92f69_idx",
        ),
        migrations.RemoveField(
            model_name="task",
            name="completed_at",
        ),
        migrations.RemoveField(
            model_name="task",
            name="due_date_time",
        ),
        migrations.RemoveField(
            model_name="task",
            name="notification",
        ),
        migrations.RemoveField(
            model_name="task",
            name="user",
        ),
        migrations.AddField(
            model_name="task",
            name="due_date",
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name="task",
            name="due_time",
            field=models.TimeField(default=datetime.time(23, 59)),
        ),
        migrations.AddField(
            model_name="task",
            name="notification_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="task",
            name="category",
            field=models.CharField(
                choices=[
                    ("Health", "Health"),
                    ("Work", "Work"),
                    ("Study", "Study"),
                    ("Personal", "Personal"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="task",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[("Pending", "Pending"), ("Completed", "Completed")],
                default="Pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="task_name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="task",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
